#!/usr/bin/env bash

# `install` Run all installers

set -e

cd $DOT

echo "› Run all installers"
find ./rel -name install.sh
printf "\n"

echo "› Start"
find ./rel -name install.sh -exec sh -c "{}" \;
